from synthesium.utils import colors

# frame thingies
DEFAULT_FRAME_WIDTH = 2000
DEFAULT_FRAME_HEIGHT = 1600
DEFAULT_FRAME_SIZE = (2000, 1600)

DEFAULT_FPS = 24
DEFAULT_BG = colors.BLACK
DEFAULT_COLOR_DEPTH = 4

FFMPEG_BIN = "ffmpeg"
